// The talk-back material of the voice chain retest (29 September 2026, app at
// 270a8e0, scratchpad brain-retest/voice): the 40 member replies that were
// voiced (inputs.json "talk": exact script text, the member's saved language
// and the actions that are right for it), and every distinct transcription the
// nine transcriber set-ups returned for them (stt-results.json and
// stt-extra-results.json, 1,080 results): Cartesia ink-whisper and OpenAI
// gpt-transcribe read twice through the app's two-language route (the member's
// reply language first, then the other; null is a failed reading), and the
// OpenAI models read once. `results` is how many of the 1,080 results gave
// exactly these readings. Used by tests/voice-talkback-retest.test.ts.
export type RetestReply = {
  id: string;
  text: string;
  lang: "en" | "ar-msa" | "ar-gulf" | "mixed";
  memberLanguage: "en" | "ar";
  category: string;
  /** The actions that are right: "done", "reps:N", "not_done", "ack", "pain", ... */
  expect: string[];
};
export const RETEST_REPLIES: RetestReply[] = [
  {"id": "tb01", "text": "Done.", "lang": "en", "memberLanguage": "en", "category": "done", "expect": ["done"]},
  {"id": "tb02", "text": "Finished, that's it.", "lang": "en", "memberLanguage": "en", "category": "done", "expect": ["done"]},
  {"id": "tb03", "text": "Eight reps.", "lang": "en", "memberLanguage": "en", "category": "numbers", "expect": ["reps:8"]},
  {"id": "tb04", "text": "I did twelve.", "lang": "en", "memberLanguage": "en", "category": "numbers", "expect": ["reps:12"]},
  {"id": "tb05", "text": "Done, ten reps at sixty kilos.", "lang": "en", "memberLanguage": "en", "category": "numbers+weight", "expect": ["reps:10"]},
  {"id": "tb06", "text": "I did six, it was too heavy.", "lang": "en", "memberLanguage": "en", "category": "numbers+weight", "expect": ["reps:6"]},
  {"id": "tb07", "text": "I didn't finish that set.", "lang": "en", "memberLanguage": "en", "category": "negated", "expect": ["not_done"]},
  {"id": "tb08", "text": "Not done yet.", "lang": "en", "memberLanguage": "en", "category": "negated", "expect": ["ack"]},
  {"id": "tb09", "text": "I almost made it.", "lang": "en", "memberLanguage": "en", "category": "hedged", "expect": ["not_done"]},
  {"id": "tb10", "text": "I didn't do the last one.", "lang": "en", "memberLanguage": "en", "category": "not_done", "expect": ["not_done"]},
  {"id": "tb11", "text": "I missed the last three reps.", "lang": "en", "memberLanguage": "en", "category": "not_done", "expect": ["not_done"]},
  {"id": "tb12", "text": "My knee hurts.", "lang": "en", "memberLanguage": "en", "category": "pain", "expect": ["pain"]},
  {"id": "tb13", "text": "I feel dizzy.", "lang": "en", "memberLanguage": "en", "category": "pain", "expect": ["pain"]},
  {"id": "tb14", "text": "Pause for a moment.", "lang": "en", "memberLanguage": "en", "category": "pause", "expect": ["pause"]},
  {"id": "tb15", "text": "Skip this one.", "lang": "en", "memberLanguage": "en", "category": "skip", "expect": ["skip"]},
  {"id": "tb16", "text": "That was way too heavy.", "lang": "en", "memberLanguage": "en", "category": "effort", "expect": ["too_heavy"]},
  {"id": "tb17", "text": "أنهيت المجموعة.", "lang": "ar-msa", "memberLanguage": "ar", "category": "done", "expect": ["done"]},
  {"id": "tb18", "text": "أكملت ثماني تكرارات.", "lang": "ar-msa", "memberLanguage": "ar", "category": "numbers", "expect": ["reps:8"]},
  {"id": "tb19", "text": "لم أكمل المجموعة الأخيرة.", "lang": "ar-msa", "memberLanguage": "ar", "category": "not_done", "expect": ["not_done"]},
  {"id": "tb20", "text": "لم أنته بعد.", "lang": "ar-msa", "memberLanguage": "ar", "category": "negated", "expect": ["ack"]},
  {"id": "tb21", "text": "أشعر بدوار.", "lang": "ar-msa", "memberLanguage": "ar", "category": "pain", "expect": ["pain"]},
  {"id": "tb22", "text": "توقف قليلاً من فضلك.", "lang": "ar-msa", "memberLanguage": "ar", "category": "pause", "expect": ["pause"]},
  {"id": "tb23", "text": "الوزن ثقيل جداً.", "lang": "ar-msa", "memberLanguage": "ar", "category": "effort", "expect": ["too_heavy"]},
  {"id": "tb24", "text": "خلصت.", "lang": "ar-gulf", "memberLanguage": "ar", "category": "done", "expect": ["done"]},
  {"id": "tb25", "text": "سويت عشر.", "lang": "ar-gulf", "memberLanguage": "ar", "category": "numbers", "expect": ["reps:10"]},
  {"id": "tb26", "text": "خلصت، سويت ثمان.", "lang": "ar-gulf", "memberLanguage": "ar", "category": "numbers", "expect": ["reps:8"]},
  {"id": "tb27", "text": "ما خلصت.", "lang": "ar-gulf", "memberLanguage": "ar", "category": "negated", "expect": ["not_done", "ack"]},
  {"id": "tb28", "text": "ما قدرت أكملها.", "lang": "ar-gulf", "memberLanguage": "ar", "category": "not_done", "expect": ["not_done"]},
  {"id": "tb29", "text": "تقريباً خلصت.", "lang": "ar-gulf", "memberLanguage": "ar", "category": "hedged", "expect": ["ack", "not_done"]},
  {"id": "tb30", "text": "ظهري يعورني.", "lang": "ar-gulf", "memberLanguage": "ar", "category": "pain", "expect": ["pain"]},
  {"id": "tb31", "text": "استنى شوي.", "lang": "ar-gulf", "memberLanguage": "ar", "category": "pause", "expect": ["pause"]},
  {"id": "tb32", "text": "طوفها.", "lang": "ar-gulf", "memberLanguage": "ar", "category": "skip", "expect": ["skip"]},
  {"id": "tb33", "text": "الوزن ثقيل وايد.", "lang": "ar-gulf", "memberLanguage": "ar", "category": "effort", "expect": ["too_heavy"]},
  {"id": "tb34", "text": "Done يا كوتش، سويت twelve.", "lang": "mixed", "memberLanguage": "ar", "category": "numbers", "expect": ["reps:12"]},
  {"id": "tb35", "text": "خلصت the set.", "lang": "mixed", "memberLanguage": "ar", "category": "done", "expect": ["done"]},
  {"id": "tb36", "text": "الوزن too heavy.", "lang": "mixed", "memberLanguage": "ar", "category": "effort", "expect": ["too_heavy"]},
  {"id": "tb37", "text": "ما قدرت أكمل the last set.", "lang": "mixed", "memberLanguage": "ar", "category": "not_done", "expect": ["not_done"]},
  {"id": "tb38", "text": "My back يعورني.", "lang": "mixed", "memberLanguage": "en", "category": "pain", "expect": ["pain"]},
  {"id": "tb39", "text": "Wait شوي، pause.", "lang": "mixed", "memberLanguage": "en", "category": "pause", "expect": ["pause"]},
  {"id": "tb40", "text": "I'm not sure I finished, تقريباً.", "lang": "mixed", "memberLanguage": "en", "category": "hedged", "expect": ["ack", "not_done", "unknown"]},
];
export type RetestReadings = { id: string; readings: Array<string | null>; results: number };
export const RETEST_READINGS: RetestReadings[] = [
  {"id": "tb01", "readings": ["Done.", "مرحبا"], "results": 2},
  {"id": "tb01", "readings": ["Done.", "ترجمة نانسي قنقر"], "results": 1},
  {"id": "tb01", "readings": ["Done."], "results": 21},
  {"id": "tb02", "readings": ["Finished. That's it.", "فنشت!"], "results": 1},
  {"id": "tb02", "readings": ["Finished. That's it."], "results": 16},
  {"id": "tb02", "readings": ["Finished. That's it.", "فنشت. تصمي."], "results": 1},
  {"id": "tb02", "readings": ["Finished. That's it.", "فنشت. فنشت."], "results": 1},
  {"id": "tb02", "readings": ["Finished, that's it."], "results": 5},
  {"id": "tb03", "readings": ["8 reps", "8 reps"], "results": 1},
  {"id": "tb03", "readings": ["8 reps", "8 ربز"], "results": 1},
  {"id": "tb03", "readings": ["Eight reps.", "8 رأس"], "results": 1},
  {"id": "tb04", "readings": ["I did 12.", "أفعل 12"], "results": 1},
  {"id": "tb04", "readings": ["I did 12.", "أقوم بقيت 12"], "results": 1},
  {"id": "tb03", "readings": ["Eight reps."], "results": 16},
  {"id": "tb04", "readings": ["I did 12.", "أقوم بقى 12"], "results": 1},
  {"id": "tb03", "readings": ["Eight reps"], "results": 1},
  {"id": "tb03", "readings": ["8 reps."], "results": 2},
  {"id": "tb05", "readings": ["Done. 10 reps at 60 kilos.", "10 ربز في 60 كيلوز"], "results": 1},
  {"id": "tb03", "readings": ["eight reps"], "results": 2},
  {"id": "tb05", "readings": ["Done. 10 reps at 60 kilos.", "10 ربما على 60 كيلوز"], "results": 1},
  {"id": "tb05", "readings": ["Done. 10 reps at 60 kilos.", "10 ربز و 60 كيلس"], "results": 1},
  {"id": "tb06", "readings": ["I did six. It was too heavy.", "أقوم بقيت 6. كانت أقوم بقيت."], "results": 1},
  {"id": "tb06", "readings": ["I did 6. It was too heavy.", "أقوم بعمل 6. كانت أقوى أقوى"], "results": 1},
  {"id": "tb04", "readings": ["I did twelve."], "results": 18},
  {"id": "tb04", "readings": ["I did 12."], "results": 2},
  {"id": "tb04", "readings": ["I did 12"], "results": 1},
  {"id": "tb07", "readings": ["I didn't finish that set.", "ألم أنه لا ينفع هذا المنزل"], "results": 1},
  {"id": "tb06", "readings": ["I did six. It was too heavy.", "أقوم بقيت 6. كانت أقل بقيت"], "results": 1},
  {"id": "tb07", "readings": ["I didn't finish that set.", "لم أقوم بإمكاني هذا المنزل"], "results": 2},
  {"id": "tb08", "readings": ["Not done yet.", "لقد أخذتها"], "results": 1},
  {"id": "tb05", "readings": ["Done! 10 reps at 60 kilos."], "results": 1},
  {"id": "tb08", "readings": ["Not done yet.", "لم يتم تقلقا"], "results": 1},
  {"id": "tb05", "readings": ["Done, 10 reps at 60 kilos."], "results": 3},
  {"id": "tb08", "readings": ["Not done yet.", "محطة."], "results": 1},
  {"id": "tb05", "readings": ["Done, ten reps at sixty kilos."], "results": 3},
  {"id": "tb05", "readings": ["Done. 10 reps at 60 kilos."], "results": 5},
  {"id": "tb05", "readings": ["Done, ten reps at 60 kilos."], "results": 2},
  {"id": "tb05", "readings": ["Done. Ten reps at sixty kilos."], "results": 2},
  {"id": "tb09", "readings": ["I almost made it.", "لقد قد أقلها"], "results": 1},
  {"id": "tb05", "readings": ["Done. Ten reps at 60 kilos."], "results": 5},
  {"id": "tb06", "readings": ["I did six. It was too heavy."], "results": 20},
  {"id": "tb09", "readings": ["I almost made it.", "لقد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد قد ق"], "results": 2},
  {"id": "tb10", "readings": ["I didn't do the last one.", "لم أفعل ذلك المرة"], "results": 1},
  {"id": "tb10", "readings": ["I didn't do the last one.", "لم أفعل ذلك الأخير"], "results": 1},
  {"id": "tb07", "readings": ["I didn't finish that set."], "results": 21},
  {"id": "tb10", "readings": ["I didn't do the last one.", "لقد أخذتها الأخير"], "results": 1},
  {"id": "tb06", "readings": ["I did sense."], "results": 1},
  {"id": "tb11", "readings": ["I missed the last three reps.", "أمس المترجمات الأخير"], "results": 1},
  {"id": "tb11", "readings": ["I missed the last three reps.", "أمس المترجمات الأخيرة"], "results": 1},
  {"id": "tb11", "readings": ["I missed the last three reps.", "أمسي الأخير من الأخير"], "results": 1},
  {"id": "tb08", "readings": ["Not done yet."], "results": 16},
  {"id": "tb12", "readings": ["My knee hurts.", "مي نيه هرس"], "results": 1},
  {"id": "tb12", "readings": ["My knee hurts", "مي نيهرس"], "results": 1},
  {"id": "tb12", "readings": ["My knee hurts", "مي نيه حرص"], "results": 1},
  {"id": "tb13", "readings": ["I feel dizzy.", "أشعر بشكل مزيد"], "results": 1},
  {"id": "tb13", "readings": ["I feel dizzy.", "أشعرني"], "results": 2},
  {"id": "tb08", "readings": ["Not done."], "results": 3},
  {"id": "tb08", "readings": ["Not done yet"], "results": 1},
  {"id": "tb08", "readings": ["Not done"], "results": 1},
  {"id": "tb09", "readings": ["I almost made it."], "results": 21},
  {"id": "tb14", "readings": ["Pause for a moment.", "توقيت للمشاهدة"], "results": 2},
  {"id": "tb14", "readings": ["Pause for a moment.", "ترجمة نانسي قنقر"], "results": 1},
  {"id": "tb15", "readings": ["Skip this one.", "سكب هذا المساعد"], "results": 1},
  {"id": "tb15", "readings": ["Skip this one.", "ستبقى هذا المشكل"], "results": 1},
  {"id": "tb15", "readings": ["Skip this one.", "ستبقى هذا"], "results": 1},
  {"id": "tb10", "readings": ["I didn't do the last one."], "results": 21},
  {"id": "tb16", "readings": ["That was way too heavy.", "هذا كان لكي أكثر"], "results": 1},
  {"id": "tb16", "readings": ["That was way too heavy.", "كانت تشعر بشكل كبير"], "results": 1},
  {"id": "tb16", "readings": ["That was way too heavy.", "كانت تشعرًا"], "results": 1},
  {"id": "tb17", "readings": ["أنهيت المجموعة", "I'm going to show you the next one."], "results": 1},
  {"id": "tb17", "readings": ["أنهيت المجموعة", "I had to stop the whole process"], "results": 1},
  {"id": "tb17", "readings": ["أنهيت المجمورة", "And here to the next one."], "results": 1},
  {"id": "tb11", "readings": ["I missed the last three reps."], "results": 19},
  {"id": "tb18", "readings": ["أكملت ثماني تكرارات", "I've done 8 more."], "results": 1},
  {"id": "tb18", "readings": ["أكملت ثماني تكرارات", "I completed 8 times."], "results": 1},
  {"id": "tb18", "readings": ["أكمل 8 تكرارات", "I have to complete 8 repeated"], "results": 1},
  {"id": "tb19", "readings": ["لم أكمل المجموعة الأخيرة", "لم أكمل المجموعة الأخيرة"], "results": 1},
  {"id": "tb19", "readings": ["لم أكمل المجموعة الأخيرة", "I didn't make the last episode."], "results": 1},
  {"id": "tb20", "readings": ["لم أنته بعد", "لم انتهوا بعد"], "results": 1},
  {"id": "tb19", "readings": ["لم أكمل المجموعة الأخيرة", "I didn't make the last part."], "results": 1},
  {"id": "tb12", "readings": ["My knee hurts."], "results": 21},
  {"id": "tb20", "readings": ["لم أنت خبار", "-"], "results": 1},
  {"id": "tb11", "readings": ["I missed the last three reps, Sweden."], "results": 1},
  {"id": "tb20", "readings": ["لم أنت خبا", "-"], "results": 1},
  {"id": "tb21", "readings": ["أشعر بدوار", "I feel like the doors"], "results": 1},
  {"id": "tb21", "readings": ["أشعر بدوار", "I feel like I'm doing it."], "results": 1},
  {"id": "tb11", "readings": ["I missed the last three reps, Peter."], "results": 1},
  {"id": "tb22", "readings": ["توقف قليلاً من فضلك", "Tawakaf Kali'na, Min Fadlik."], "results": 1},
  {"id": "tb21", "readings": ["أشعر بدوار", "I'm feeling the same."], "results": 1},
  {"id": "tb22", "readings": ["توقف قليلا من فضلك", "You have a long time."], "results": 1},
  {"id": "tb22", "readings": ["توقف قليلا من فضلك", "\"You've been a long time for you.\""], "results": 1},
  {"id": "tb13", "readings": ["I feel dizzy."], "results": 21},
  {"id": "tb23", "readings": ["الوزن ثقيل جدا", "The weight is very difficult."], "results": 1},
  {"id": "tb23", "readings": ["الوزن ثقيل جداً", "The weight is very difficult."], "results": 1},
  {"id": "tb14", "readings": ["Pause for a moment."], "results": 21},
  {"id": "tb24", "readings": ["هلست", "Hollast."], "results": 1},
  {"id": "tb23", "readings": ["الوزن فقيل جداً", "The weather is very difficult"], "results": 1},
  {"id": "tb24", "readings": ["هالله", "Hallows."], "results": 1},
  {"id": "tb24", "readings": ["هل أصدقنا؟", "Hallas."], "results": 1},
  {"id": "tb25", "readings": ["سويت عشر", "10"], "results": 1},
  {"id": "tb25", "readings": ["سويت عشر", "So it 10"], "results": 1},
  {"id": "tb15", "readings": ["Skip this one."], "results": 18},
  {"id": "tb15", "readings": ["スキップする。"], "results": 1},
  {"id": "tb26", "readings": ["هلست؟ سويت ثمان", "Ha lust, so wait the man."], "results": 1},
  {"id": "tb25", "readings": ["صوت عشر", "So what I should"], "results": 1},
  {"id": "tb26", "readings": ["حلست؟ سويت ثمان", "Ha lust, so wait the man."], "results": 1},
  {"id": "tb26", "readings": ["هل ست؟ سويت ثمان", "Ha lust? So wait the man."], "results": 1},
  {"id": "tb27", "readings": ["ما خلصت", "What did you do?"], "results": 1},
  {"id": "tb16", "readings": ["That was way too heavy."], "results": 19},
  {"id": "tb27", "readings": ["ما خلصت", "I didn't finish"], "results": 1},
  {"id": "tb27", "readings": ["مغم", "-"], "results": 1},
  {"id": "tb15", "readings": ["スキップします。"], "results": 1},
  {"id": "tb28", "readings": ["ما قدرت أكملها؟", "ما قدرت أكملها؟"], "results": 1},
  {"id": "tb28", "readings": ["ما قدرت أكملها", "I couldn't make it."], "results": 1},
  {"id": "tb28", "readings": ["لا قدرت أكملها", "I couldn't finish this."], "results": 1},
  {"id": "tb29", "readings": ["تقريبا خلصت", "I think it's done."], "results": 1},
  {"id": "tb29", "readings": ["تقريبا خلصت", "I was almost finished."], "results": 1},
  {"id": "tb29", "readings": ["تقريبا خلصت", "It was almost impossible."], "results": 1},
  {"id": "tb17", "readings": ["أنهيت المجموعة."], "results": 18},
  {"id": "tb30", "readings": ["ظهري يعورني", "Vahri, Yaowarmi."], "results": 1},
  {"id": "tb15", "readings": ["Skip this one"], "results": 1},
  {"id": "tb30", "readings": ["ظهري يعورني", "Vahri, he made me."], "results": 1},
  {"id": "tb30", "readings": ["فهري يعوّرني", "Vahri, he awwere me."], "results": 1},
  {"id": "tb31", "readings": ["استنى شوي", "Wait a little bit."], "results": 1},
  {"id": "tb31", "readings": ["استنى شوي", "So everyone can die"], "results": 1},
  {"id": "tb32", "readings": ["طوفا", "2."], "results": 1},
  {"id": "tb31", "readings": ["استنى شوية", "-"], "results": 1},
  {"id": "tb32", "readings": ["مطلوب", "- What's that?"], "results": 1},
  {"id": "tb18", "readings": ["أكملت ثماني تكرارات."], "results": 10},
  {"id": "tb32", "readings": ["أمي", "How are you?"], "results": 1},
  {"id": "tb16", "readings": ["That was way too heavy"], "results": 2},
  {"id": "tb18", "readings": ["أكمل ثماني تكرارات."], "results": 8},
  {"id": "tb17", "readings": ["أنهيت المجموعة"], "results": 2},
  {"id": "tb33", "readings": ["الوزن ثقيل وايد", "The weight is very wide"], "results": 1},
  {"id": "tb33", "readings": ["الوزن ثقيل وعد", "The wasn't the Geen Wild"], "results": 1},
  {"id": "tb34", "readings": ["دون يا كوچ. سويت 12.", "Done, ya coach. So wait, 12."], "results": 1},
  {"id": "tb19", "readings": ["لم أكمل المجموعة الأخيرة."], "results": 15},
  {"id": "tb18", "readings": ["أكملت سماني تكرارات."], "results": 1},
  {"id": "tb19", "readings": ["لنكمل المجموعة الأخيرة."], "results": 1},
  {"id": "tb34", "readings": ["أعطى 12", "Done, ya coach. So wait, 12."], "results": 1},
  {"id": "tb33", "readings": ["الوزن ثقيل وايد", "The weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight of the weight"], "results": 1},
  {"id": "tb17", "readings": ["and hate him much more."], "results": 1},
  {"id": "tb34", "readings": ["أعطى يا كوش. سويت 12.", "Done, ya coach. So wait, 12."], "results": 1},
  {"id": "tb35", "readings": ["خلصت نسات", "End the set."], "results": 1},
  {"id": "tb35", "readings": ["خلصت تسد", "I finished the set."], "results": 1},
  {"id": "tb19", "readings": ["لبكمل المجموعة الأخيرة."], "results": 1},
  {"id": "tb20", "readings": ["لم ينتهوا بعد."], "results": 2},
  {"id": "tb20", "readings": ["لم أنتحب بعد."], "results": 1},
  {"id": "tb20", "readings": ["لم أنت حبعت؟"], "results": 1},
  {"id": "tb20", "readings": ["Let me enter."], "results": 1},
  {"id": "tb20", "readings": ["لم أنته بعد."], "results": 6},
  {"id": "tb35", "readings": ["خلصت the set", "- I lost the set."], "results": 1},
  {"id": "tb36", "readings": ["إنه ليس كبير", "It wasn't too heavy."], "results": 2},
  {"id": "tb36", "readings": ["وليس كذلك", "and he wasn't too heavy."], "results": 1},
  {"id": "tb19", "readings": ["لم أكمل المجموعة الأخيرة"], "results": 1},
  {"id": "tb18", "readings": ["أكمل سماني تكرارات"], "results": 1},
  {"id": "tb37", "readings": ["ما قدر تكمل دلاسات", "I can't keep the last set."], "results": 1},
  {"id": "tb21", "readings": ["أشعر بدوار."], "results": 14},
  {"id": "tb21", "readings": ["أشوري بدوا"], "results": 1},
  {"id": "tb19", "readings": ["لأكمل المجموعة الأخيرة."], "results": 1},
  {"id": "tb20", "readings": ["لم أنت."], "results": 1},
  {"id": "tb20", "readings": ["let me enter"], "results": 1},
  {"id": "tb20", "readings": ["لم أنت حب بعد."], "results": 1},
  {"id": "tb18", "readings": ["أكمل سناني تكرارات"], "results": 1},
  {"id": "tb19", "readings": ["لم اكمل المجموعة الاخيرة"], "results": 2},
  {"id": "tb37", "readings": ["ما قدرت أكمل الثلاث سات", "I couldn't get the last set."], "results": 1},
  {"id": "tb37", "readings": ["لا تستطيع التكمل الثلاثات", "I can't complete the last set."], "results": 1},
  {"id": "tb38", "readings": ["My back, Yaorani.", "مي باك يعورني"], "results": 1},
  {"id": "tb38", "readings": ["My back, ya orni.", "مي باك يعورني"], "results": 1},
  {"id": "tb39", "readings": ["Wei Chui, pause.", "ويكسي، توقيت"], "results": 1},
  {"id": "tb38", "readings": ["My back is out of me.", "مي باك يعورني"], "results": 1},
  {"id": "tb20", "readings": ["لم أنت حبعد."], "results": 1},
  {"id": "tb20", "readings": ["למען תחובת"], "results": 1},
  {"id": "tb20", "readings": ["Lem enthebau."], "results": 1},
  {"id": "tb22", "readings": ["توقف قليلاً من فضلك."], "results": 8},
  {"id": "tb22", "readings": ["توقف قليلا، من فضلك."], "results": 2},
  {"id": "tb20", "readings": ["Lem entekhubaʕ."], "results": 1},
  {"id": "tb22", "readings": ["توقف قليلا من فضلك."], "results": 4},
  {"id": "tb20", "readings": ["لم أنت غبار."], "results": 1},
  {"id": "tb21", "readings": ["Ashwali bidiwah."], "results": 1},
  {"id": "tb39", "readings": ["Wait Shui, pause.", "ويشوى، ازالي"], "results": 1},
  {"id": "tb39", "readings": ["Wei Chui, pause.", "ويشوان، قوز"], "results": 1},
  {"id": "tb22", "readings": ["وقدتين من"], "results": 1},
  {"id": "tb20", "readings": ["لم انتهوا بعد"], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished, takriban.", "أم لا أعرف أنه قريبا"], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished the kriban.", "لا أعرف أنني أخذت تقريبا"], "results": 1},
  {"id": "tb21", "readings": ["أشعر بدوار"], "results": 3},
  {"id": "tb40", "readings": ["I'm not sure I finished the Kriban.", "لا أعرف أنه قد أخذ العربة"], "results": 1},
  {"id": "tb23", "readings": ["الوزن ثقيل جدا."], "results": 18},
  {"id": "tb22", "readings": ["وكتلي من فضل."], "results": 1},
  {"id": "tb21", "readings": ["أشهر بدوار."], "results": 1},
  {"id": "tb20", "readings": ["لم أنتهوا بعد"], "results": 1},
  {"id": "tb21", "readings": ["أشهر البدوار."], "results": 1},
  {"id": "tb24", "readings": ["حلّصت."], "results": 1},
  {"id": "tb24", "readings": ["هلست"], "results": 1},
  {"id": "tb24", "readings": ["Hallas."], "results": 5},
  {"id": "tb24", "readings": ["خلصت."], "results": 3},
  {"id": "tb24", "readings": ["حلّصت"], "results": 1},
  {"id": "tb22", "readings": ["لقد قفزت من فضلك."], "results": 1},
  {"id": "tb24", "readings": ["خلص."], "results": 5},
  {"id": "tb22", "readings": ["توقفت ليلى من فضلك."], "results": 1},
  {"id": "tb22", "readings": ["توقف قليلا من فضلك"], "results": 2},
  {"id": "tb25", "readings": ["سويت عشر"], "results": 5},
  {"id": "tb25", "readings": ["سوات عشر."], "results": 5},
  {"id": "tb22", "readings": ["توقف قليلاً من فضلك"], "results": 1},
  {"id": "tb25", "readings": ["تسعة عشر"], "results": 2},
  {"id": "tb24", "readings": ["خلصت"], "results": 1},
  {"id": "tb25", "readings": ["所為他神"], "results": 1},
  {"id": "tb25", "readings": ["sowie Pasche."], "results": 1},
  {"id": "tb24", "readings": ["Halas."], "results": 1},
  {"id": "tb23", "readings": ["الوزن فقيل جدا"], "results": 3},
  {"id": "tb25", "readings": ["سويت عشر."], "results": 4},
  {"id": "tb26", "readings": ["خلصت، سويت ثمان."], "results": 9},
  {"id": "tb26", "readings": ["خلصت؟ انتظر"], "results": 1},
  {"id": "tb24", "readings": ["Hallast."], "results": 1},
  {"id": "tb24", "readings": ["HALLASIN!"], "results": 2},
  {"id": "tb26", "readings": ["خلصت، سأويت"], "results": 1},
  {"id": "tb26", "readings": ["خلصت،await"], "results": 1},
  {"id": "tb27", "readings": ["ما خلصت."], "results": 11},
  {"id": "tb26", "readings": ["خلصت، سويت تمام."], "results": 2},
  {"id": "tb26", "readings": ["خلصت؟ So wait ثمان."], "results": 1},
  {"id": "tb25", "readings": ["سوۃ عشر"], "results": 1},
  {"id": "tb27", "readings": ["ما خلصت"], "results": 5},
  {"id": "tb27", "readings": ["ما خلص"], "results": 3},
  {"id": "tb25", "readings": ["سوېپښ."], "results": 1},
  {"id": "tb27", "readings": ["ما خلص."], "results": 1},
  {"id": "tb26", "readings": ["خلصت؟ سويت ثمان؟"], "results": 1},
  {"id": "tb28", "readings": ["ما قدرت أكملها."], "results": 9},
  {"id": "tb28", "readings": ["ما جدرت أكملها."], "results": 1},
  {"id": "tb28", "readings": ["لا، بدرت أكملها."], "results": 1},
  {"id": "tb28", "readings": ["أنا أريد أن أكمل"], "results": 1},
  {"id": "tb26", "readings": ["خلصت؟ So wait for man"], "results": 1},
  {"id": "tb26", "readings": ["خلصت سويت ثمان."], "results": 1},
  {"id": "tb28", "readings": ["لا أقدر أكملها."], "results": 1},
  {"id": "tb26", "readings": ["حلصت، ساويت ثمان"], "results": 1},
  {"id": "tb28", "readings": ["أنا بيدارتي أكمل"], "results": 1},
  {"id": "tb25", "readings": ["Sowetošan"], "results": 1},
  {"id": "tb29", "readings": ["تقريباً خلصت."], "results": 15},
  {"id": "tb26", "readings": ["حلصت! ساويت ثمان!"], "results": 2},
  {"id": "tb29", "readings": ["تقريباً خلص."], "results": 2},
  {"id": "tb30", "readings": ["ظهري يعورني."], "results": 11},
  {"id": "tb28", "readings": ["لا قدرت أكملها"], "results": 1},
  {"id": "tb30", "readings": ["وخري يعورني."], "results": 2},
  {"id": "tb30", "readings": ["ضهري يعورني."], "results": 1},
  {"id": "tb28", "readings": ["نا بقدرش أكمل."], "results": 2},
  {"id": "tb28", "readings": ["لا قدرت أكملها."], "results": 1},
  {"id": "tb30", "readings": ["البحر يعورم"], "results": 1},
  {"id": "tb31", "readings": ["استنى شوي."], "results": 11},
  {"id": "tb27", "readings": ["ما خمسة"], "results": 1},
  {"id": "tb31", "readings": ["استنى شوي"], "results": 5},
  {"id": "tb29", "readings": ["تقريبا خلصت."], "results": 1},
  {"id": "tb30", "readings": ["بحري يعورني."], "results": 2},
  {"id": "tb28", "readings": ["ما قدرت أكملها"], "results": 3},
  {"id": "tb31", "readings": ["Ist das nicht schön?"], "results": 1},
  {"id": "tb32", "readings": ["Τόφα."], "results": 1},
  {"id": "tb32", "readings": ["多萨。"], "results": 1},
  {"id": "tb32", "readings": ["طوفة."], "results": 3},
  {"id": "tb31", "readings": ["Istte näisvõi?"], "results": 1},
  {"id": "tb32", "readings": ["도파"], "results": 2},
  {"id": "tb30", "readings": ["ظهري يعورني"], "results": 3},
  {"id": "tb32", "readings": ["多麼多煩"], "results": 1},
  {"id": "tb32", "readings": ["Both."], "results": 1},
  {"id": "tb33", "readings": ["الوزن ثقيل وايد."], "results": 12},
  {"id": "tb29", "readings": ["تقريباً خلصت"], "results": 2},
  {"id": "tb32", "readings": ["What the?"], "results": 1},
  {"id": "tb31", "readings": ["Istana Sway."], "results": 1},
  {"id": "tb32", "readings": ["What the fuck?"], "results": 1},
  {"id": "tb32", "readings": ["多反。"], "results": 1},
  {"id": "tb33", "readings": ["الوزن ثقيل وايد"], "results": 2},
  {"id": "tb31", "readings": ["Ist denn nicht so?"], "results": 1},
  {"id": "tb33", "readings": ["الوزن ثقيل واحد."], "results": 2},
  {"id": "tb29", "readings": ["تقريبا"], "results": 1},
  {"id": "tb34", "readings": ["Done, ya coach. So wait, twelve."], "results": 8},
  {"id": "tb32", "readings": ["shiftin."], "results": 1},
  {"id": "tb32", "readings": ["Tofa"], "results": 1},
  {"id": "tb32", "readings": ["Dorfan."], "results": 1},
  {"id": "tb33", "readings": ["الوزن ثقيل واحد"], "results": 2},
  {"id": "tb34", "readings": ["Done, ya coach. So wait, 12."], "results": 2},
  {"id": "tb34", "readings": ["Done Yakoch, so wait twelve."], "results": 1},
  {"id": "tb30", "readings": ["ظَهْرِي يَعَوَّرْنِي"], "results": 1},
  {"id": "tb32", "readings": ["Dochaan."], "results": 1},
  {"id": "tb32", "readings": ["Docha"], "results": 1},
  {"id": "tb32", "readings": ["Justine."], "results": 1},
  {"id": "tb35", "readings": ["خلصت."], "results": 6},
  {"id": "tb35", "readings": ["خلصت السات"], "results": 1},
  {"id": "tb33", "readings": ["الوزن تقيل واجد."], "results": 2},
  {"id": "tb35", "readings": ["خلصت الست"], "results": 3},
  {"id": "tb34", "readings": ["Done, ya coach. So weight twelve."], "results": 1},
  {"id": "tb34", "readings": ["Done, Yakoch. So wait, twelve."], "results": 1},
  {"id": "tb36", "readings": ["الوزن. Too heavy."], "results": 2},
  {"id": "tb34", "readings": ["Done Yakoucha."], "results": 1},
  {"id": "tb36", "readings": ["It wasn't too heavy."], "results": 16},
  {"id": "tb36", "readings": ["الوزن too heavy."], "results": 2},
  {"id": "tb34", "readings": ["Dan Jacobs."], "results": 1},
  {"id": "tb34", "readings": ["Dan jakoč, sawejt twelf."], "results": 1},
  {"id": "tb34", "readings": ["Dan yakoc. Sa wait, twelf."], "results": 1},
  {"id": "tb35", "readings": ["خلصت ساعات"], "results": 1},
  {"id": "tb34", "readings": ["Dan Jacobz: 12."], "results": 1},
  {"id": "tb35", "readings": ["خلصت الست."], "results": 5},
  {"id": "tb35", "readings": ["خلصت سات."], "results": 2},
  {"id": "tb34", "readings": ["Dan jakouč, sawejt 12."], "results": 1},
  {"id": "tb37", "readings": ["ما تقدر تكمل The Last Set."], "results": 2},
  {"id": "tb37", "readings": ["ما أقدر تكمل The Last Set."], "results": 1},
  {"id": "tb31", "readings": ["استنى شوية"], "results": 1},
  {"id": "tb37", "readings": ["ما قدرت أكمل ثلاث ساعات."], "results": 3},
  {"id": "tb37", "readings": ["ما أقدر أكمل The Last Set."], "results": 1},
  {"id": "tb32", "readings": ["Tofa."], "results": 1},
  {"id": "tb37", "readings": ["ما قدرت أكمل دراستي."], "results": 5},
  {"id": "tb37", "readings": ["ما تقدر تكمل ثلاث ساعات."], "results": 1},
  {"id": "tb38", "readings": ["My back yawrni."], "results": 1},
  {"id": "tb37", "readings": ["ما تقدر تكمل ثلاث ست."], "results": 1},
  {"id": "tb38", "readings": ["My back yaourni."], "results": 1},
  {"id": "tb38", "readings": ["My back, yaourni."], "results": 1},
  {"id": "tb32", "readings": ["どうさ"], "results": 1},
  {"id": "tb38", "readings": ["My back, yaurni."], "results": 1},
  {"id": "tb37", "readings": ["ماذا تكمل دراستك؟"], "results": 1},
  {"id": "tb38", "readings": ["My back yaurni."], "results": 1},
  {"id": "tb38", "readings": ["My back yawned."], "results": 1},
  {"id": "tb38", "readings": ["Мой бак? Я ору."], "results": 1},
  {"id": "tb37", "readings": ["ما قدرت أكمل دراسة"], "results": 1},
  {"id": "tb39", "readings": ["Wait, should I pause."], "results": 4},
  {"id": "tb36", "readings": ["It was too heavy."], "results": 1},
  {"id": "tb37", "readings": ["ما قدرت أكمل ثلاث ستات."], "results": 1},
  {"id": "tb38", "readings": ["My back, yaurne."], "results": 1},
  {"id": "tb39", "readings": ["Wait, pause."], "results": 2},
  {"id": "tb38", "readings": ["My back? Yeah, I wouldn't make it."], "results": 2},
  {"id": "tb39", "readings": ["which way? Pause."], "results": 2},
  {"id": "tb39", "readings": ["Which way? Pause."], "results": 3},
  {"id": "tb38", "readings": ["My back,"], "results": 1},
  {"id": "tb37", "readings": ["متى تكمل دراستك؟"], "results": 1},
  {"id": "tb38", "readings": ["Mai back iaw rni."], "results": 1},
  {"id": "tb33", "readings": ["الوزن ثقيل وايض"], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished the qareeban."], "results": 1},
  {"id": "tb39", "readings": ["Waitchwell, pause."], "results": 1},
  {"id": "tb32", "readings": ["To wstał."], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished the kareeba."], "results": 3},
  {"id": "tb38", "readings": ["Mai back yauri."], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished, taqriban."], "results": 2},
  {"id": "tb40", "readings": ["I'm not sure I finished, تقريبا."], "results": 5},
  {"id": "tb38", "readings": ["Мой бак, я урни."], "results": 1},
  {"id": "tb38", "readings": ["Mai back iauurni."], "results": 1},
  {"id": "tb38", "readings": ["My back?"], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished, taqrīban."], "results": 1},
  {"id": "tb38", "readings": ["My back ya ur me."], "results": 1},
  {"id": "tb39", "readings": ["Weichwe, pause."], "results": 1},
  {"id": "tb39", "readings": ["Wait swiwe, pause."], "results": 1},
  {"id": "tb39", "readings": ["Waitschwe, pause."], "results": 1},
  {"id": "tb39", "readings": ["Wejwej, pause."], "results": 1},
  {"id": "tb38", "readings": ["My back? Ya, aur mein?"], "results": 1},
  {"id": "tb39", "readings": ["Huicue, pause."], "results": 1},
  {"id": "tb39", "readings": ["Weitermachen."], "results": 1},
  {"id": "tb34", "readings": ["Done, ya coach. So wait 12."], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished. تقريباً"], "results": 1},
  {"id": "tb39", "readings": ["Weiche, pos!"], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished."], "results": 2},
  {"id": "tb34", "readings": ["Done, ya coach. So weight, 12."], "results": 1},
  {"id": "tb40", "readings": ["تقريبا."], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished, تقريباً."], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished تقريباً"], "results": 1},
  {"id": "tb35", "readings": ["I finished the set."], "results": 1},
  {"id": "tb35", "readings": ["خلصت the set"], "results": 1},
  {"id": "tb35", "readings": ["خلصت الجزء"], "results": 1},
  {"id": "tb37", "readings": ["ما أقدر تكمّل ضلاسات."], "results": 1},
  {"id": "tb37", "readings": ["ما تقدر تكمّل ظلال سات"], "results": 1},
  {"id": "tb38", "readings": ["My back yawni."], "results": 1},
  {"id": "tb37", "readings": ["ما أقدر تكمّل ضلاسات"], "results": 1},
  {"id": "tb38", "readings": ["My back yawned at me."], "results": 1},
  {"id": "tb39", "readings": ["Wait, Shui. Pause."], "results": 1},
  {"id": "tb38", "readings": ["My back? Yeah, I would admit it."], "results": 1},
  {"id": "tb39", "readings": ["Weichui, pause."], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished, da kribben."], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished the kribbe."], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished the Kribat."], "results": 1},
  {"id": "tb01", "readings": ["Done.", "Done."], "results": 3},
  {"id": "tb02", "readings": ["Finished. That's it.", "Finished, that's it."], "results": 1},
  {"id": "tb02", "readings": ["Finished. That's it.", "Finished. That's it."], "results": 2},
  {"id": "tb03", "readings": ["Eight reps.", "Eight reps."], "results": 3},
  {"id": "tb04", "readings": ["I did twelve.", "I did twelve."], "results": 3},
  {"id": "tb05", "readings": ["Done. Ten reps at 60 kilos.", "Done. Ten reps at 60 kilos."], "results": 1},
  {"id": "tb05", "readings": ["Done. 10 reps at 60 kilos.", "Done. Ten reps at 60 kilos."], "results": 1},
  {"id": "tb05", "readings": ["Done, 10 reps at 60 kilos.", "Done, 10 reps at 60 kilos."], "results": 1},
  {"id": "tb06", "readings": ["I did six. It was too heavy.", "I did six. It was too heavy."], "results": 3},
  {"id": "tb07", "readings": ["I didn't finish that set.", "I didn't finish that set."], "results": 1},
  {"id": "tb07", "readings": ["I didn't finish that set.", "لم أنهي تلك المجموعة."], "results": 2},
  {"id": "tb08", "readings": ["Not done yet.", "Not done yet."], "results": 3},
  {"id": "tb09", "readings": ["I almost made it.", "I almost made it."], "results": 3},
  {"id": "tb10", "readings": ["I didn't do the last one.", "I didn't do the last one."], "results": 3},
  {"id": "tb11", "readings": ["I missed the last three reps.", "I missed the last three reps."], "results": 3},
  {"id": "tb12", "readings": ["My knee hurts.", "My knee hurts."], "results": 3},
  {"id": "tb13", "readings": ["I feel dizzy.", "I feel dizzy."], "results": 3},
  {"id": "tb14", "readings": ["Pause for a moment.", "Pause for a moment."], "results": 3},
  {"id": "tb15", "readings": ["Skip this one.", "Skip this one."], "results": 3},
  {"id": "tb16", "readings": ["That was way too heavy.", "That was way too heavy."], "results": 3},
  {"id": "tb17", "readings": ["أنهيت المجموعة.", "أنهيت المجموعة."], "results": 3},
  {"id": "tb18", "readings": ["أكمل ثماني تكرارات.", "أكمل ثماني تكرارات."], "results": 2},
  {"id": "tb18", "readings": ["أكملت ثماني تكرارات.", "أكملت ثماني تكرارات."], "results": 1},
  {"id": "tb19", "readings": ["لم أكمل المجموعة الأخيرة.", "لم أكمل المجموعة الأخيرة."], "results": 3},
  {"id": "tb20", "readings": ["لم أنته بعد.", "لم أنته بعد."], "results": 2},
  {"id": "tb20", "readings": ["لم أنت غبار.", "لم أنت."], "results": 1},
  {"id": "tb21", "readings": ["أشعر بدوار.", "أشعر بدوار."], "results": 3},
  {"id": "tb22", "readings": ["توقف قليلاً من فضلك.", "توقف قليلاً من فضلك."], "results": 3},
  {"id": "tb23", "readings": ["الوزن ثقيل جدا.", "الوزن ثقيل جدا."], "results": 3},
  {"id": "tb24", "readings": ["خلص.", "خلص."], "results": 2},
  {"id": "tb24", "readings": ["خلصت.", "خلصت."], "results": 1},
  {"id": "tb25", "readings": ["سويت عشر.", "سويت عشر."], "results": 1},
  {"id": "tb25", "readings": ["سوات عشر.", "زويت عشر."], "results": 1},
  {"id": "tb25", "readings": ["سويت عشر.", "So what?"], "results": 1},
  {"id": "tb26", "readings": ["خلصت، سويت ثمان.", "خلصت، سويت ثمان."], "results": 2},
  {"id": "tb26", "readings": ["خلصت، سويت ثمان.", "خلصت، so wait ثمان."], "results": 1},
  {"id": "tb27", "readings": ["ما خلصت.", "ما خلصت."], "results": 3},
  {"id": "tb28", "readings": ["ما قدرت أكملها.", "ما قدرت أكملها."], "results": 3},
  {"id": "tb29", "readings": ["تقريباً خلصت.", "تقريباً خلصت."], "results": 2},
  {"id": "tb29", "readings": ["تقريباً خلص.", "تقريباً خلص."], "results": 1},
  {"id": "tb30", "readings": ["ظهري يعورني.", "ظهري يعورني."], "results": 3},
  {"id": "tb31", "readings": ["استنى شوي.", "استنى شوي."], "results": 3},
  {"id": "tb32", "readings": ["طوفة.", "Τόφα."], "results": 1},
  {"id": "tb32", "readings": ["طوفة.", "Dorsa."], "results": 1},
  {"id": "tb33", "readings": ["الوزن ثقيل وايد.", "الوزن ثقيل وايد."], "results": 3},
  {"id": "tb32", "readings": ["طوفة.", "Both."], "results": 1},
  {"id": "tb34", "readings": ["Done, ya coach. So wait, twelve.", "Done, ya coach. So wait, twelve."], "results": 3},
  {"id": "tb35", "readings": ["خلصت.", "خلصت."], "results": 3},
  {"id": "tb36", "readings": ["الوزن. Too heavy.", "الوزن. Too heavy."], "results": 1},
  {"id": "tb36", "readings": ["الوزن too heavy.", "It wasn't too heavy."], "results": 2},
  {"id": "tb37", "readings": ["ما أقدر أكمل The Last Set.", "ما أقدر أكمل The Last Set."], "results": 1},
  {"id": "tb37", "readings": ["ما تقدر تكمل The Last Set.", "ما تقدر تكمل The Last Set."], "results": 1},
  {"id": "tb37", "readings": ["ما تقدر تكمل ثلاث ست.", "ما تقدر تكمل ثلاث ساعات."], "results": 1},
  {"id": "tb38", "readings": ["My back yaourni.", "My back يعورني."], "results": 1},
  {"id": "tb38", "readings": ["My back yaurni.", "My back يعورني."], "results": 1},
  {"id": "tb39", "readings": ["Wait, should I pause.", "Wait, شوي. Pause."], "results": 1},
  {"id": "tb38", "readings": ["My back yawned.", "My back, يعورني."], "results": 1},
  {"id": "tb39", "readings": ["Wait, should I pause.", "Wait, should I pause."], "results": 1},
  {"id": "tb39", "readings": ["Wait, pause.", "Wait شوي. Pause."], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished, taqriban.", "I'm not sure I finished, تقريبا."], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished the kareeba.", "I'm not sure I finished, تقريبا."], "results": 1},
  {"id": "tb40", "readings": ["I'm not sure I finished the kareeba.", "I'm not sure I finished, تقريباً."], "results": 1},
];
