"use client";
import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { TrainingHoldNotice } from "./coaching-completion";
import { ChatAttachmentList, ChatAttachmentPicker, type ChatAttachment } from "./chat-attachments";
import { CoachingFollowups } from "./coaching-followups";

async function api(path: string, method = "GET", body?: unknown) {
  const r = await fetch("/api/v1" + path, { method, credentials: "same-origin", headers: body === undefined ? undefined : { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
  const d = await r.json(); if (!r.ok) throw new Error(d.message ?? "Request failed"); return d;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function useTraining(userId?: string) {
  const [data, setData] = useState<any>(), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("");
  const load = useCallback(async () => { const result = await api("/training/overview" + (userId ? "?subscriberId=" + userId : "")); setData(result); return result; }, [userId]);
  useEffect(() => { void load().catch((e) => setError(e.message)); }, [load]);
  async function action(fn: () => Promise<any>, success = "Saved") { setBusy(true); setError(""); setMessage(""); try { const r = await fn(); await load(); setMessage(success); return r; } catch (e) { setError((e as Error).message); return null; } finally { setBusy(false); } }
  return { data, busy, message, error, action, load };
}
const exercise = () => ({ name: "", sets: 3, reps: 10, restSeconds: 90, loadKg: 0, rir: 2, cue: "", demonstrationUrl: "", alternatives: [] as any[] });
function cleanExercise(e: any) { const { demonstrationUrl, ...rest } = e; return { ...rest, ...(demonstrationUrl ? { demonstrationUrl } : {}) }; }
function ExerciseEditor({ values, onChange, library }: { values: any[]; onChange: (values: any[]) => void; library: any[] }) {
  const patch = (i: number, key: string, value: any) => onChange(values.map((e, j) => j === i ? { ...e, [key]: value } : e));
  return <div>{values.map((e, i) => <fieldset key={i} style={{ marginBlock: 16 }}><legend>Exercise {i + 1}</legend>
    {library.length > 0 && <Field label="Use a library exercise"><select value="" onChange={(event) => { const found = library.find((v) => v.id === event.target.value); if (found) { const { allowedUses, ...prescription } = found.data; onChange(values.map((v, j) => j === i ? { ...exercise(), ...prescription } : v)); } }}><option value="">Choose an exercise</option>{library.map((v) => <option key={v.id} value={v.id}>{v.data.name}</option>)}</select></Field>}
    <Field label="Exercise name"><input value={e.name} required maxLength={100} onChange={(event) => patch(i, "name", event.target.value)} /></Field>
    <div className="form-grid">{[["sets", "Sets", 1, 10], ["reps", "Repetitions", 1, 100], ["loadKg", "Load (kg)", 0, 500], ["restSeconds", "Rest (seconds)", 0, 600], ["rir", "Repetitions in reserve", 0, 10]].map(([key, label, min, max]) => <Field key={String(key)} label={String(label)}><input type="number" min={Number(min)} max={Number(max)} step={key === "loadKg" ? 0.5 : 1} value={e[String(key)]} onChange={(event) => patch(i, String(key), Number(event.target.value))} required /></Field>)}</div>
    <Field label="Coaching cue"><textarea value={e.cue} onChange={(event) => patch(i, "cue", event.target.value)} maxLength={1000} rows={2} /></Field>
    <Field label="Demonstration link (HTTPS)"><input type="url" value={e.demonstrationUrl ?? ""} onChange={(event) => patch(i, "demonstrationUrl", event.target.value)} placeholder="https://" /></Field>
    <Field label="Approved alternative"><input value={e.alternatives[0]?.name ?? ""} placeholder="Optional alternative exercise" onChange={(event) => patch(i, "alternatives", event.target.value ? [{ name: event.target.value, loadKg: e.alternatives[0]?.loadKg ?? 0, cue: e.alternatives[0]?.cue ?? "" }] : [])} /></Field>
    {e.alternatives.length > 0 && <div className="form-grid"><Field label="Alternative load (kg)"><input type="number" min={0} max={500} step={0.5} value={e.alternatives[0].loadKg} onChange={(event) => patch(i, "alternatives", [{ ...e.alternatives[0], loadKg: Number(event.target.value) }])} /></Field><Field label="Alternative cue"><input value={e.alternatives[0].cue} onChange={(event) => patch(i, "alternatives", [{ ...e.alternatives[0], cue: event.target.value }])} /></Field></div>}
    {values.length > 1 && <button type="button" className="text-button" onClick={() => onChange(values.filter((_, j) => j !== i))}>Remove exercise</button>}
  </fieldset>)}<button type="button" className="button secondary" disabled={values.length >= 20} onClick={() => onChange([...values, exercise()])}>Add exercise</button></div>;
}
const dateToday = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Dubai", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
export function TrainingPrograms({ state }: { state: any }) {
  const sub = state.user.role === "subscriber", [selected, setSelected] = useState(""), t = useTraining(sub ? state.user.userId : selected || undefined), router = useRouter();
  const [sessions, setSessions] = useState([{ label: "Session A", weekday: 1, exercises: [exercise()] }]), [library, setLibrary] = useState<any[]>([]);
  useEffect(() => { if (!sub) void api("/training/exercises").then(setLibrary).catch(() => {}); }, [sub]);
  const programs = t.data?.records.filter((r: any) => r.kind === "program" && ["assigned", "template"].includes(r.status)) ?? [], planned = t.data?.records.filter((r: any) => r.kind === "planned_session").sort((a: any, b: any) => a.data.date.localeCompare(b.data.date)) ?? [];
  return <><div className="page-heading"><h1>{sub ? "Your training plan" : "Programs and training calendar"}</h1><p className="muted">Multiweek plans, clear prescriptions and flexible training days.</p></div>
    {t.error && <p role="alert" className="notice">{t.error}</p>}{t.message && <p role="status" className="notice">{t.message}</p>}
    {t.data && <TrainingHoldNotice records={t.data.records} />}
    {!sub && <><section className="card"><h2>Create a program</h2><form onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void t.action(() => api("/programs", "POST", { program: { title: f.get("title"), goal: f.get("goal"), daysPerWeek: sessions.length, weeks: Number(f.get("weeks")), exercises: sessions[0].exercises.map(cleanExercise), sessions: sessions.map((s) => ({ ...s, exercises: s.exercises.map(cleanExercise) })) }, ...(f.get("subscriber") ? { subscriberId: f.get("subscriber"), startDate: f.get("startDate"), timezone: f.get("timezone") } : {}) }), "Program and calendar saved"); }}>
      <div className="form-grid"><Field label="Program name"><input name="title" required maxLength={120} /></Field><Field label="Training goal"><input name="goal" required maxLength={1000} /></Field><Field label="Number of weeks"><input name="weeks" type="number" min={1} max={26} defaultValue={4} required /></Field><Field label="Assign to"><select name="subscriber"><option value="">Save as my template</option>{(t.data?.members ?? []).map((m: any) => <option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Start date"><input name="startDate" type="date" defaultValue={dateToday()} required /></Field><Field label="Calendar timezone"><input name="timezone" defaultValue="Asia/Dubai" required /></Field></div>
      {sessions.map((s, i) => <fieldset key={i} style={{ marginBlock: 24 }}><legend>Training day {i + 1}</legend><div className="form-grid"><Field label="Session name"><input value={s.label} required onChange={(e) => setSessions((v) => v.map((x, j) => j === i ? { ...x, label: e.target.value } : x))} /></Field><Field label="Weekday"><select value={s.weekday} onChange={(e) => setSessions((v) => v.map((x, j) => j === i ? { ...x, weekday: Number(e.target.value) } : x))}>{["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].map((name, day) => <option key={name} value={day}>{name}</option>)}</select></Field></div><ExerciseEditor values={s.exercises} library={library} onChange={(values) => setSessions((v) => v.map((x, j) => j === i ? { ...x, exercises: values } : x))} />{sessions.length > 1 && <button type="button" className="text-button" onClick={() => setSessions((v) => v.filter((_, j) => j !== i))}>Remove training day</button>}</fieldset>)}
      <div className="button-row"><button type="button" className="button secondary" disabled={sessions.length >= 7} onClick={() => setSessions((v) => [...v, { label: `Session ${String.fromCharCode(65 + v.length)}`, weekday: [0, 1, 2, 3, 4, 5, 6].find((d) => !v.some((s) => s.weekday === d)) ?? 0, exercises: [exercise()] }])}>Add training day</button><button className="button" disabled={t.busy} type="submit">Save program</button><button type="button" className="button secondary" disabled={t.busy || !sessions[0].exercises[0].name} onClick={() => void t.action(async () => { await api("/training/exercises", "POST", cleanExercise(sessions[0].exercises[0])); setLibrary(await api("/training/exercises")); }, "First exercise saved to your library")}>Save first exercise to library</button></div>
    </form></section><Field label="View a client's plans"><select value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">All clients and templates</option>{(t.data?.members ?? []).map((m: any) => <option key={m.id} value={m.id}>{m.name}</option>)}</select></Field></>}
    <div className="two-columns">{programs.map((p: any) => <section key={p.id} className="card"><span className="badge">{p.status}</span><h2>{p.data.title}</h2><p>{p.data.goal}</p><p className="muted">{p.data.weeks ?? 4} weeks · {p.data.daysPerWeek} sessions each week</p>{p.data.exercises.map((e: any) => <p key={e.name}><strong>{e.name}</strong> · {e.sets} × {e.reps} · {e.loadKg} kg · {e.restSeconds}s rest · {e.rir ?? 2} reps in reserve</p>)}
      {!sub && p.status === "template" && <form onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void t.action(() => api(`/programs/${p.id}/assign`, "POST", { version: p.version, subscriberId: f.get("subscriber"), startDate: f.get("date"), timezone: "Asia/Dubai" }), "Template assigned with a training calendar"); }}><Field label="Client"><select name="subscriber" required><option value="">Choose a client</option>{(t.data?.members ?? []).map((m: any) => <option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="First week starts"><input name="date" type="date" defaultValue={dateToday()} required /></Field><button className="button" type="submit" disabled={t.busy}>Assign template</button></form>}
      {!sub && p.status === "assigned" && <ProgramProgression program={p} busy={t.busy} action={t.action} />}
      {sub && !planned.some((s: any) => s.data.programId === p.id && s.status === "planned") && <button className="button" disabled={t.busy} onClick={() => void t.action(() => api("/workouts/start", "POST", { programId: p.id }), "Workout ready").then((r) => r && router.push(`/app/workouts/${r.id}`))}>Start workout</button>}
    </section>)}</div>
    <section className="card"><h2>Training calendar</h2>{!planned.length && <p>{sub ? "Your trainer will assign your training calendar." : "Assign a program to create the client's sessions."}</p>}{planned.map((p: any) => <article key={p.id} style={{ borderTop: "1px solid var(--line)", paddingBlock: 16 }}><h3>{p.data.date} · {p.data.label}</h3><p className="muted">Week {p.data.week} · {p.data.timezone} · {p.status}</p>{p.status === "planned" && <><div className="button-row">{sub && <button className="button" disabled={t.busy} onClick={() => void t.action(() => api("/workouts/start", "POST", { programId: p.data.programId, plannedSessionId: p.id }), "Session started").then((r) => r && router.push(`/app/workouts/${r.id}`))}>Start this session</button>}<button className="button secondary" disabled={t.busy} onClick={() => { const note = window.prompt("Why are you skipping this session?"); if (note) void t.action(() => api(`/training/sessions/${p.id}/cancel`, "POST", { version: p.version, note }), "Session skipped"); }}>Skip session</button></div><details><summary>Move this session</summary><form onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void t.action(() => api(`/training/sessions/${p.id}/reschedule`, "POST", { version: p.version, date: f.get("date"), note: f.get("note") }), "Session moved"); }}><Field label="New date"><input type="date" name="date" defaultValue={p.data.date} min={dateToday()} required /></Field><Field label="Reason"><input name="note" required minLength={3} /></Field><button className="button secondary" disabled={t.busy} type="submit">Save date</button></form></details></>}{p.status === "started" && sub && <a href={`/app/workouts/${p.data.workoutId}`}>Continue session</a>}</article>)}</section>
  </>;
}
function ProgramProgression({ program, busy, action }: { program: any; busy: boolean; action: (fn: () => Promise<any>, message?: string) => Promise<any> }) {
  const exercises = [...program.data.exercises, ...(program.data.sessions ?? []).flatMap((s: any) => s.exercises)].filter((e: any, i: number, all: any[]) => all.findIndex((v) => v.name === e.name) === i), [name, setName] = useState(exercises[0]?.name ?? ""), selected = exercises.find((e: any) => e.name === name) ?? exercises[0];
  return <details><summary>Revise an exercise</summary><Field label="Exercise to revise"><select value={name} onChange={(e) => setName(e.target.value)}>{exercises.map((e: any) => <option key={e.name}>{e.name}</option>)}</select></Field><form key={name} onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void action(() => api(`/programs/${program.id}/progression`, "POST", { version: program.version, exercise: name, loadKg: Number(f.get("loadKg")), reps: Number(f.get("reps")), rir: Number(f.get("rir")), note: f.get("note") }), "Future sessions now use the revised prescription"); }}><div className="form-grid"><Field label="Load (kg)"><input name="loadKg" type="number" min={0} max={500} step={0.5} defaultValue={selected?.loadKg ?? 0} required /></Field><Field label="Repetitions"><input name="reps" type="number" min={1} max={100} defaultValue={selected?.reps ?? 10} required /></Field><Field label="Repetitions in reserve"><input name="rir" type="number" min={0} max={10} defaultValue={selected?.rir ?? 2} required /></Field></div><Field label="Reason and coaching instructions"><textarea name="note" required minLength={10} rows={2} /></Field><button type="submit" className="button" disabled={busy}>Update future sessions</button></form></details>;
}

export function WorkoutTools({ workout, userId, onChange }: { workout: any; userId: string; onChange?: () => Promise<void> | void }) {
  const t = useTraining(userId), [seconds, setSeconds] = useState(0), [until, setUntil] = useState<number | null>(null);
  useEffect(() => { if (!until) return; const tick = () => { const left = Math.max(0, Math.ceil((until - Date.now()) / 1000)); setSeconds(left); if (!left) setUntil(null); }; tick(); const interval = setInterval(tick, 250); return () => clearInterval(interval); }, [until]);
  const current = t.data?.records.find((r: any) => r.id === workout.id) ?? workout, sets = t.data?.sets.filter((s: any) => s.workout_id === current.id) ?? [];
  async function act(fn: () => Promise<any>, success: string) { const r = await t.action(fn, success); if (r) await onChange?.(); }
  return <section className="card"><h2>Session tools</h2>{t.error && <p role="alert" className="notice">{t.error}</p>}{t.message && <p role="status" className="notice">{t.message}</p>}
    <div className="button-row"><strong role="timer" aria-live="off">Rest: {Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, "0")}</strong>{[60, 90, 120].map((s) => <button key={s} className="button secondary" onClick={() => setUntil(Date.now() + s * 1000)}>{s}s</button>)}<button className="text-button" onClick={() => { setUntil(null); setSeconds(0); }}>Reset timer</button></div>
    {current.data.program.exercises.map((e: any) => <div key={e.name} style={{ marginBlock: 16 }}><strong>{e.name}</strong><span className="muted"> · Target {e.rir ?? 2} repetitions in reserve</span><div className="button-row"><button className="text-button" onClick={() => setUntil(Date.now() + e.restSeconds * 1000)}>Start prescribed {e.restSeconds}s rest</button>{e.demonstrationUrl && <a target="_blank" rel="noreferrer" href={e.demonstrationUrl}>Watch demonstration</a>}</div>{e.alternatives?.length > 0 && current.status === "active" && <details><summary>Approved alternatives</summary><p className="muted">Use these when equipment is unavailable. Report pain with the safety control.</p>{e.alternatives.map((v: any) => <button key={v.name} className="button secondary" disabled={t.busy} onClick={() => void act(() => api(`/workouts/${current.id}/substitute`, "POST", { version: current.version, exercise: e.name, replacement: v.name, reason: "equipment_unavailable" }), "Approved alternative applied")}>{v.name} · {v.loadKg} kg</button>)}</details>}</div>)}
    <details><summary>Review and correct saved sets</summary><button className="text-button" onClick={() => void t.load()}>Refresh saved logs</button>{!sets.length && <p>No saved set logs yet. Reconnect and sync any device logs first.</p>}{sets.map((s: any) => { const revision = Math.max(0, ...(t.data?.records.filter((r: any) => r.kind === "workout_correction" && r.data.eventId === s.id).map((r: any) => r.data.revision) ?? [])); return <form key={s.id + ":" + revision} onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void act(() => api(`/workouts/${current.id}/sets/${s.id}/correct`, "POST", { revision, reps: Number(f.get("reps")), loadKg: Number(f.get("loadKg")), rir: Number(f.get("rir")), note: f.get("note") }), "Log correction recorded"); }}><h3>{s.data.exercise} · set {s.data.set}</h3><div className="form-grid"><Field label="Actual repetitions"><input type="number" name="reps" min={0} max={200} defaultValue={s.data.reps} required /></Field><Field label="Actual load (kg)"><input type="number" name="loadKg" min={0} max={500} step={0.5} defaultValue={s.data.loadKg} required /></Field><Field label="Actual repetitions in reserve"><input type="number" name="rir" min={0} max={10} defaultValue={s.data.rir ?? 2} required /></Field></div><Field label="Correction reason"><input name="note" minLength={3} required /></Field><button className="button secondary" disabled={t.busy} type="submit">Save correction</button></form>; })}</details>
    {current.status === "active" && <button className="text-button" disabled={t.busy} onClick={() => { const note = window.prompt("Why are you ending this session early?"); if (note) void act(() => api(`/workouts/${current.id}/abandon`, "POST", { note }), "Session ended without marking it complete"); }}>End this session early</button>}
  </section>;
}

export function TrainingProgress({ state }: { state: any }) {
  const sub = state.user.role === "subscriber", [selected, setSelected] = useState(sub ? state.user.userId : state.members?.find((m: any) => m.role === "subscriber")?.id ?? ""), t = useTraining(selected || undefined);
  const rows = t.data?.records ?? [], workouts = rows.filter((r: any) => r.kind === "workout"), byExercise = new Map<string, { sets: number; volume: number; maxLoad: number; last: string }>();
  for (const s of t.data?.sets ?? []) { const v = byExercise.get(s.data.exercise) ?? { sets: 0, volume: 0, maxLoad: 0, last: s.created_at }; v.sets++; v.volume += s.data.reps * s.data.loadKg; v.maxLoad = Math.max(v.maxLoad, s.data.loadKg); byExercise.set(s.data.exercise, v); }
  return <><h1>Training progress</h1><p className="muted">Saved workout performance with your latest corrections applied.</p>{!sub && <Field label="Client"><select value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">Select a client</option>{state.members?.filter((m: any) => m.role === "subscriber").map((m: any) => <option key={m.id} value={m.id}>{m.name}</option>)}</select></Field>}{t.error && <p role="alert">{t.error}</p>}<section className="card"><h2>{workouts.filter((w: any) => w.status === "completed").length} completed sessions</h2><p>{(t.data?.sets ?? []).length} logged sets · {rows.filter((r: any) => r.kind === "planned_session" && r.status === "planned").length} planned sessions remaining</p><div style={{ overflowX: "auto" }}><table><thead><tr><th>Exercise</th><th>Sets</th><th>Volume (kg)</th><th>Highest load (kg)</th><th>Last logged</th></tr></thead><tbody>{[...byExercise].map(([name, v]) => <tr key={name}><td>{name}</td><td>{v.sets}</td><td>{Math.round(v.volume * 10) / 10}</td><td>{v.maxLoad}</td><td>{new Date(v.last).toLocaleDateString()}</td></tr>)}</tbody></table></div>{!byExercise.size && <p>Complete and log a workout to see your progress here.</p>}{t.data?.partial && <p className="muted">This view contains the most recent available records.</p>}</section><section className="card"><h2>Session history</h2>{workouts.map((w: any) => <p key={w.id}>{sub ? <a href={`/app/workouts/${w.id}`}>{w.data.program.title}</a> : w.data.program.title} · {new Date(w.created_at).toLocaleDateString()} · {w.status.replaceAll("_", " ")}</p>)}</section></>;
}

export function CoachingMessages({ state }: { state: any }) {
  const sub = state.user.role === "subscriber", [target, setTarget] = useState(sub ? state.user.userId : state.members?.find((m: any) => m.role === "subscriber")?.id ?? ""), [messages, setMessages] = useState<any[]>([]), [hasMore, setHasMore] = useState(false), [personal, setPersonal] = useState(false), [text, setText] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [attachments, setAttachments] = useState<ChatAttachment[]>([]), [uploading, setUploading] = useState(false), [composerKey, setComposerKey] = useState(0);
  const currentTarget = useRef(target); currentTarget.current = target;
  const load = useCallback(async (before?: string) => { if (!target) return; const result = await api("/messages/thread?subscriberId=" + target + (before ? "&before=" + before : "")); if (currentTarget.current !== target) return; setMessages((old) => before ? [...result.messages, ...old] : [...old.filter((m) => !result.messages.some((r: any) => r.id === m.id)), ...result.messages].sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime())); if (before || !messages.length) setHasMore(result.hasMore); setPersonal(result.personalReview); }, [target]);
  useEffect(() => { setMessages([]); setError(""); void load().catch((e) => setError(e.message)); const timer = setInterval(() => { if (document.visibilityState === "visible") void load().catch(() => {}); }, 8000); return () => clearInterval(timer); }, [load]);
  async function send(digital: boolean) { if (busy || uploading || (digital && attachments.length)) return; setBusy(true); setError(""); setNotice(""); try { const result = await api(digital ? "/coaching/ask" : "/messages", "POST", digital ? { message: text } : { text, subscriberId: target, attachmentIds: attachments.map((file) => file.id) }); setText(""); setAttachments([]); setComposerKey((v) => v + 1); if (result.pendingReview) setNotice(result.message); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <><h1>{sub ? "Talk with your coach" : "Client conversations"}</h1><p className="muted">New messages refresh while this page is open. Digital responses are labelled.</p>{!sub && <Field label="Client"><select value={target} disabled={busy || uploading} onChange={(e) => { setTarget(e.target.value); setText(""); setAttachments([]); setNotice(""); }}><option value="">Choose a client</option>{state.members?.filter((m: any) => m.role === "subscriber").map((m: any) => <option key={m.id} value={m.id}>{m.name}</option>)}</select></Field>}{error && <p role="alert" className="notice">{error}</p>}{notice && <p role="status" className="notice">{notice}</p>}{personal && <p className="notice">Your trainer is handling this conversation personally.</p>}{!sub && target && <button className="button secondary" disabled={busy || uploading} onClick={async () => { setBusy(true); try { await api("/takeover", "POST", { subscriberId: target, active: !personal }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>{personal ? "Return to qualified digital coaching" : "Take over this conversation"}</button>}
    <section className="card" aria-label="Conversation"><div aria-live="polite">{hasMore && messages.length > 0 && <button className="text-button" onClick={() => void load(messages[0].id).catch((e) => setError(e.message))}>Load earlier messages</button>}{messages.map((m) => <article key={m.id} style={{ borderBottom: "1px solid var(--line)", paddingBlock: 16 }}><small className="muted">{m.data.author?.replaceAll("_", " ")}{m.data.scheduled ? " · scheduled by coach" : ""} · {new Date(m.created_at).toLocaleString()}</small><p style={{ whiteSpace: "pre-wrap" }}>{m.data.text}</p><ChatAttachmentList files={m.data.attachments ?? []} user={state.user} onRemove={(id) => setMessages((old) => old.map((message) => message.id === m.id ? { ...message, data: { ...message.data, attachments: message.data.attachments.filter((file: ChatAttachment) => file.id !== id) } } : message))} /></article>)}{!messages.length && <p>No messages yet.</p>}</div><form onSubmit={(event) => { event.preventDefault(); void send(false); }}><Field label="Your message"><textarea value={text} onChange={(e) => setText(e.target.value)} required={!attachments.length} maxLength={4000} rows={4} /></Field><ChatAttachmentPicker key={target + ":" + composerKey} subjectId={target} files={attachments} user={state.user} onChange={setAttachments} onBusy={setUploading} disabled={busy} />{sub && <p className="muted">Photos and PDFs go to your trainer. The digital coach does not read attachments.</p>}<div className="button-row"><button className="button" disabled={busy || uploading || !target || (!text.trim() && !attachments.length)} type="submit">Send to {sub ? "trainer" : "client"}</button>{sub && <button className="button secondary" disabled={busy || uploading || !!attachments.length || !text.trim()} type="button" onClick={() => void send(true)}>Ask digital coach</button>}</div></form></section>
    {!sub && target && <CoachingFollowups key={target} subscriberId={target} user={state.user} />}
  </>;
}
